close #22 interfaces created
BuenosCodes/etitango-front pull request #51
Opened 2022-08-06 22:21 UTC by rusonariga

2022-09-07 18:06 UTC, thehighestprimenumber requested changes

2022-09-12 14:31 UTC, rusonariga commented on shared/event_administration.ts
> +interface AdministrationTShirt {
es para la gestion del pedido de remeras, desde el punto de vista del admin

2022-09-12 18:01 UTC, rusonariga commented on shared/event_accountability.ts
> +interface AccountabilityItem {
como se hace para leer lo importado arriba?

2023-01-15 14:55 UTC, thehighestprimenumber commented
closing stale PR

2023-01-15 14:55 UTC, closed without merging