feat: export signups to csv file
BuenosCodes/etitango-front pull request #75
Opened 2022-09-01 15:22 UTC by amartinezsaucedo

Closes #68

Por ahora se están exportando todos los campos de las inscripciones. En caso de querer cambiarlo se pueden filtrar. Usamos la librería `react-csv`

2022-09-01 15:55 UTC, thehighestprimenumber requested changes

2022-09-01 15:55 UTC, thehighestprimenumber commented on src/modules/inscripcion/InscripcionList.jsx
> +                      <CSVLink data={inscripciones} filename={t('exportFilename')}>
cambiaría para que el filename incluya la fecha

2022-09-01 15:55 UTC, thehighestprimenumber commented on src/modules/inscripcion/InscripcionList.jsx
> +                            <IconButton
Agregaría un texto que diga "Descargar para excel" o algo así porque creo que la gente que no entiende mucho de computadoras no va a entender el iconito

2022-09-01 15:55 UTC, thehighestprimenumber commented on src/modules/inscripcion/InscripcionList.jsx
> +                      <CSVLink data={inscripciones} filename={t('exportFilename')}>
Tendríamos que traducir las cabeceras de los campos porque el csv dice cosas como "nameLast" en vez de "Apellido"

2022-09-03 00:35 UTC, amartinezsaucedo commented on src/modules/inscripcion/InscripcionList.jsx
> +                            <IconButton
Si, me había parecido más discreto el ícono, pero es cierto que no se va a entender. Si queremos cambiar el label avisame :)

2022-09-03 00:37 UTC, amartinezsaucedo commented
Listos los cambios! Agregué un pequeño fix que se me comió en un review a la hora de parsear una variable de los tipos que vienen de Firebase a un primitivo de js

2022-09-08 22:44 UTC, thehighestprimenumber approved these changes

2022-09-08 22:44 UTC, merged